name       : python-flaky
version    : 3.5.3
release    : 3
source     :
    - https://github.com/box/flaky/archive/v3.5.3.tar.gz : 57f3b11b70e32ad5f03712966130aeeabb64aa8ba6e1c0b89278261877f1c0a5
license    : Apache-2.0
component  : programming.python
summary    : Plugin for nose or py.test that automatically reruns flaky tests
description: |
    Ideally, tests reliably pass or fail, but sometimes test fixtures must rely on components that aren't 100% reliable. With flaky, instead of removing those tests or marking them to @skip, they can be automatically retried.
builddeps  :
    - python-genty
    - python-mock
    - python-nose
    - python-pytest
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        export PYTHONPATH=$installdir/usr/lib/python2.7/site-packages
        nosetests-2.7 --with-flaky --exclude="test_nose_options_example" test/test_nose/
        py.test -k 'example and not options' --doctest-modules test/test_pytest/
        py.test -p no:flaky test/test_pytest/test_flaky_pytest_plugin.py
        nosetests-2.7 --with-flaky --force-flaky --max-runs 2 test/test_nose/test_nose_options_example.py
        py.test --force-flaky --max-runs 2 test/test_pytest/test_pytest_options_example.py
    popd

    pushd $PKG_BUILD_DIR/py3build
        export PYTHONPATH=$installdir/usr/lib/python%python3_version%/site-packages
        nosetests-%python3_version% --with-flaky --exclude="test_nose_options_example" test/test_nose/
        py.test3 -k 'example and not options' --doctest-modules test/test_pytest/
        py.test3 -p no:flaky test/test_pytest/test_flaky_pytest_plugin.py
        nosetests-%python3_version% --with-flaky --force-flaky --max-runs 2 test/test_nose/test_nose_options_example.py
        py.test3 --force-flaky --max-runs 2 test/test_pytest/test_pytest_options_example.py
    popd
