name       : python-flaky
version    : 3.7.0
release    : 7
source     :
    - https://github.com/box/flaky/archive/v3.7.0.tar.gz : d2d0c482ef43211e9ef23213dd83ec1b2686c1510a5ac83624b7d6b41710c3eb
license    : Apache-2.0
component  : programming.python
summary    : Plugin for nose or py.test that automatically reruns flaky tests
description: |
    Ideally, tests reliably pass or fail, but sometimes test fixtures must rely on components that aren't 100% reliable. With flaky, instead of removing those tests or marking them to @skip, they can be automatically retried.
builddeps  :
    - python-genty
    - python-mock
    - python-nose
    - python-pytest
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        export PYTHONPATH=$installdir/usr/lib/python2.7/site-packages
        nosetests-2.7 --with-flaky --exclude="test_nose_options_example" test/test_nose/
        py.test -k 'example and not options' --doctest-modules test/test_pytest/
        py.test -p no:flaky test/test_pytest/test_flaky_pytest_plugin.py
        nosetests-2.7 --with-flaky --force-flaky --max-runs 2 test/test_nose/test_nose_options_example.py
        py.test --force-flaky --max-runs 2 test/test_pytest/test_pytest_options_example.py
    popd

    pushd $PKG_BUILD_DIR/py3build
        export PYTHONPATH=$installdir/usr/lib/python%python3_version%/site-packages
        nosetests-%python3_version% --with-flaky --exclude="test_nose_options_example" test/test_nose/
        py.test3 -k 'example and not options' --doctest-modules test/test_pytest/
        py.test3 -p no:flaky test/test_pytest/test_flaky_pytest_plugin.py
        nosetests-%python3_version% --with-flaky --force-flaky --max-runs 2 test/test_nose/test_nose_options_example.py
        py.test3 --force-flaky --max-runs 2 test/test_pytest/test_pytest_options_example.py
    popd
